<a href="https://colab.research.google.com/github/kavyasasikumar07/ML-basics/blob/main/Gradient_Descent_Calculus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x_data = np.array([-40, -10, 0, 8, 15, 22], dtype=float) # Celcius
y_data = np.array([-40, 14, 32, 46, 59, 72], dtype=float) # Farenhite

In [ ]:
x = 22
m = 1.8
c = 32

y = x * m + c
print(y)

71.6


In [ ]:
x_data * m + c

array([-40. ,  14. ,  32. ,  46.4,  59. ,  71.6])

In [ ]:
m = 1
c = 1

y_pred = x_data * m + c
print(y_pred)

[-39.  -9.   1.   9.  16.  23.]


In [ ]:
y_data

array([-40.,  14.,  32.,  46.,  59.,  72.])

## Error Calculation MEthod

In [ ]:
print(y_pred - y_data) # residual/error
print((y_pred - y_data)**2) # if u sum the error as it is the +ve and -ve vals will get cancel out each other
print(np.sum((y_pred - y_data)**2)/len(y_data))
print(np.mean((y_pred - y_data)**2))

[  1. -23. -31. -37. -43. -49.]
[1.000e+00 5.290e+02 9.610e+02 1.369e+03 1.849e+03 2.401e+03]
1185.0
1185.0


In [ ]:
def error(y, y_hat):
  return np.mean((y - y_hat)**2)

In [ ]:
error(y_data, y_pred)

1185.0

## RAndom search value of c

In [ ]:
m = 1.8
c_vals = [25,26,27,28,29,30,31,32,33,34]

for cc in c_vals:
  y_pred = x_data * m + cc
  # print(y_pred)
  print(cc, error(y_data, y_pred))

25 49.05333333333335
26 36.05333333333335
27 25.053333333333345
28 16.05333333333334
29 9.05333333333334
30 4.053333333333338
31 1.0533333333333361
32 0.0533333333333339
33 1.0533333333333315
34 4.053333333333329


```
c = 30, 32, 34, 36
m = 1, 1.5, 2. 2.5

16 combination

c = 1 to 40 (step = 1) 40
m = 0 to 4 (step = 0.1) 40

1600
```

In [ ]:
m = 1
c = 50

y_pred = x_data * m + c
print(y_pred)
print(error(y_data, y_pred))

[10. 40. 50. 58. 65. 72.]
613.3333333333334


In [ ]:
x = np.array([-40, -10, 0, 8, 15, 22], dtype=float)
y = np.array([-40, 14, 32, 46, 59, 72], dtype=float)

In [ ]:
m = 1
c = 1
lr = 0.001

n = len(x)

y_hat = m * x + c
print(y_hat)
e = error(y,y_hat)
print(m, c, e)

#These are partial derivatives of the error with respect to m and c using the gradient of the mean squared error loss function.

de_dm = (-2/n) * np.sum(x * (y - y_hat))
de_dc = (-2/n) * np.sum(y - y_hat)

print("***")
print(de_dm, de_dc)
m = m - (lr * de_dm)
c = c - (lr * de_dc)
print(m,c)
y_hat = m * x + c
print(y_hat)
e = error(y,y_hat)

print(m, c, e)


[-39.  -9.   1.   9.  16.  23.]
1 1 1185.0
***
-609.6666666666666 -60.666666666666664
1.6096666666666666 1.0606666666666666
[-63.326      -15.036        1.06066667  13.938       25.20566667
  36.47333333]
1.6096666666666666 1.0606666666666666 962.7677954999998


In [ ]:
print(de_dm, de_dc)


-609.6666666666666 -60.666666666666664


In [ ]:
m = -1000
c = -1000
lr = 0.001
epochs = 5000

n = len(x)
+
for i in range(epochs):
  y_hat = m * x + c
  #print(y_hat)
  e = error(y, y_hat)
  if i%50 == 0:
    print(m, c, e)

  de_dm = (-2/n) * np.sum(x * (y - y_hat))
  de_dc = (-2/n) * np.sum(y - y_hat)
  m = m - (lr * de_dm)
  c = c - (lr * de_dc)


-1000 -1000 412995600.1666667
-0.09414046303916644 -903.6900260666728 874044.2917934192
0.08620811345969655 -814.7056729015914 715705.8543052323
0.2494055303252847 -734.1837366605912 586051.3891176303
0.3970828637905104 -661.3194410245796 479884.61995055835
0.5307160746480097 -595.384543947071 392950.6076196656
0.6516407597371462 -535.7200592406132 321765.2210882673
0.7610655005637296 -481.72967034075 263475.50087683887
0.860083942465312 -432.8737704213964 215745.31849132932
0.9496857250471392 -388.664069295574 176661.74934241918
1.0307663731330905 -348.6587132001826 144658.40678068224
1.1041362470865919 -312.457868689513 118452.66463820853
1.170528641955542 -279.6997265007311 96994.25228915304
1.230607116388086 -250.05688545197714 79423.1620281457
1.2849721245681116 -223.233080231954 65035.18178346271
1.3341670174532945 -198.96022037691046 53253.671789129585
1.378683473295084 -176.99571084107544 43606.45408476387
1.4189664117159313 -157.12002738099295 35706.888623274346
1.455418440457

In [ ]:
print(m,c)

1.8021724730031106 31.954619918999597


## TensorFlow Gradients

In [ ]:
import tensorflow as tf

In [ ]:
x = tf.Variable(3.0)

x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [ ]:
y = x**2
print(y)

tf.Tensor(9.0, shape=(), dtype=float32)


In [ ]:
# Manually calculate gradient
dy_dx = 2*x
print(dy_dx)

tf.Tensor(6.0, shape=(), dtype=float32)


In [ ]:
with tf.GradientTape() as tape:
  y = x**2

In [ ]:
dy_dx = tape.gradient(y, x)
dy_dx.numpy()

6.0

In [ ]:
2*x**2 + 5*x

<tf.Tensor: shape=(), dtype=float32, numpy=33.0>

In [ ]:
with tf.GradientTape() as tape:
  y = 2*x**2 + 5*x

dy_dx = tape.gradient(y, x)
dy_dx.numpy()

17.0

In [ ]:
4 * x + 5

<tf.Tensor: shape=(), dtype=float32, numpy=17.0>

In [ ]:
with tf.GradientTape() as tape:
  y = tf.math.sin(x**2)

dy_dx = tape.gradient(y, x)
dy_dx.numpy()

-5.4667816

In [ ]:
with tf.GradientTape() as tape:
  y = x**2
  z = 2 * y**2

dz_dx = tape.gradient(z, x)
dz_dx.numpy()

216.0

In [ ]:
x = tf.Variable(1.5)
with tf.GradientTape() as tape:
  y = tf.math.sin(x**2)

dy_dx = tape.gradient(y, x)
dy_dx.numpy()

-1.884521

In [ ]:
# w = tf.Variable(tf.random.normal((3, 2)), name='w')
# b = tf.Variable(tf.zeros(2, dtype=tf.float32), name='b')
# x = [[1., 2., 3.]]

# with tf.GradientTape(persistent=True) as tape:
#   y = x @ w + b
# loss = tf.reduce_mean(y**2)

In [ ]:
loss

<tf.Tensor: shape=(), dtype=float32, numpy=5.2843766>

## Using TensorFlow Gradients

In [ ]:
import tensorflow as tf

In [ ]:
x = np.array([-40, -10, 0, 8, 15, 22], dtype=float)
y = np.array([-40, 14, 32, 46, 59, 72], dtype=float)

In [ ]:
# Error Function/Loss Function
def error(y_hat):
  return tf.reduce_mean((y - y_hat)**2)

In [ ]:
# weights
m = tf.Variable(1.0)
c = tf.Variable(0.0)

# Hyper parameters
learning_rate = 0.001 # slow learning
epoch = 2000

# there is also adaptive learning rate algos (adam, rmsprop)

# error values for plotting
error_vals = []
m_vals = []
c_vals = []
n = len(x)

# learning loop
for i in range(epoch):

  with tf.GradientTape(persistent=True) as tape:
    # forward propagation (matrix multiplication)
    y_hat = m * x + c # model

    # MSE (Loss Function)
    mse = error(y_hat)
    if i%100 == 0:
      print("m = %.2f, c = %.2f, mse = %.2f" % (m, c, mse))

  [de_dm, de_dc] = tape.gradient(mse, [m, c])

  # #### Back Prop
  # # Compute  Gradients
  # de_dm = (-2/n) * np.sum(x * (y - y_hat)) # rate of change of e w.r.t m
  # de_dc = (-2/n) * np.sum(y - y_hat) # rate of change of e w.r.t c

  # Update the weights
  m.assign_sub(de_dm * learning_rate)
  c.assign_sub(de_dc * learning_rate)


m = 1.00, c = 0.00, mse = 1246.67
m = 1.75, c = 5.80, mse = 685.64
m = 1.76, c = 10.54, mse = 459.74
m = 1.77, c = 14.43, mse = 308.27
m = 1.77, c = 17.61, mse = 206.72
m = 1.78, c = 20.22, mse = 138.62
m = 1.78, c = 22.35, mse = 92.96
m = 1.79, c = 24.10, mse = 62.35
m = 1.79, c = 25.53, mse = 41.82
m = 1.79, c = 26.71, mse = 28.06
m = 1.79, c = 27.66, mse = 18.83
m = 1.80, c = 28.45, mse = 12.64
m = 1.80, c = 29.09, mse = 8.49
m = 1.80, c = 29.62, mse = 5.71
m = 1.80, c = 30.05, mse = 3.85
m = 1.80, c = 30.41, mse = 2.60
m = 1.80, c = 30.69, mse = 1.76
m = 1.80, c = 30.93, mse = 1.20
m = 1.80, c = 31.13, mse = 0.82
m = 1.80, c = 31.28, mse = 0.57


In [ ]:
print(m,c)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.801077> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=31.414099>


## Clasroom taskk

In [ ]:
# # use a real dataset for the above code
# x = sqftarea
# y = price

In [ ]:
## Task 2

# modify the above algrithm for univariate (3 variables)

# y = m1x1 + m2x2 + mx3 + c

m1 = 0
m2 = 0
m3 = 0
c = 1

de_dm1 =
de_dm2 =
de_dm3 =
de_dc =

m1 = m1 - lr * de_dm1

SyntaxError: ignored