<a href="https://colab.research.google.com/github/kavyasasikumar07/ML-basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy


In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4,5]
l.append(7)
print(l)


[1, 2, 3, 4, 5, 7]


In [ ]:
a=np.array([1,4,3,7,1,7,8,5])
print(a)
a.shape

[1 4 3 7 1 7 8 5]


(8,)

In [ ]:
b=np.array([[1,2],[4,5]])
print(b)

[[1 2]
 [4 5]]


In [ ]:
sequence_of_integers=np.arange(5,12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [ ]:
a=np.array([1,2,3],dtype=np.float64)
b=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(type(a))
print(a.shape)
print(type(b))
print(b.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.ones([4,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.random.random(3)

array([0.63794585, 0.44323887, 0.09560931])

In [ ]:
x=np.array([1,2])
y=np.array([1.0,2.0])
z=np.array([[1,2],[3,4],[5,6]])
print(x.dtype,y.dtype,z.dtype)

int64 float64 int64


In [ ]:
np.ones((4,3,2))


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.random.random((4,3,2))

array([[[0.31509381, 0.39317804],
        [0.52425364, 0.21429647],
        [0.70359535, 0.49584834]],

       [[0.26730905, 0.60116391],
        [0.79157003, 0.62850894],
        [0.43597015, 0.19947634]],

       [[0.38682933, 0.46388405],
        [0.14389326, 0.85389809],
        [0.92594703, 0.01189104]],

       [[0.03877857, 0.96314372],
        [0.03504428, 0.84321745],
        [0.27351758, 0.34802732]]])

In [ ]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [ ]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
c=np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
f=np.arange(10,50,5)
print(f)

[10 15 20 25 30 35 40 45]


linspace=it splits equivalently between the ranges(it gives 5 numbers within 0 to 1)

In [ ]:
g=np.linspace(0.,1.,num=5)
print(g)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
g=np.linspace(1,2,5)
print(g)

[1.   1.25 1.5  1.75 2.  ]


In [ ]:
a=np.array([1,2,3])
print(a[1])

2


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[0,1])

2


In [ ]:
print(a[1:3])

[[3 4]
 [5 6]]


In [ ]:
print(a[0:2,0])

[1 3]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.shape

(3, 4)

In [ ]:
b=a[:2,1:3]
b

array([[2, 3],
       [6, 7]])

In [ ]:
b=a[0:3,0:4]
b

array([[77,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

a slice of an array is a view into the data,so modifying it will modify the original array

In [ ]:
a[0,0]=77
a


array([[77,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

While slicing,it becomes a nested array

In [ ]:
a=([[1,2,3,4],[2,3,4,5],[5,6,7,8]])
#1=a[1,1]
r2=a[1:2,:]
r3=a[[1],:]
print(r1,r1.shape)
print(r2,r2.shape)
print(r3,r3.shape)

TypeError: ignored

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,8,9,-3,2,4,7,9])
print(np.argmax(a))


2


In [ ]:
print(np.argmin(a))

3


In [ ]:
print(np.argsort(a))

[3 0 4 5 6 1 2 7]


In [ ]:
print(np.argsort(a)[::-1])

[7 2 1 6 5 4 0 3]


In [ ]:
print(np.where(a>5)[0])

[1 2 6 7]


In [ ]:
a=[0]
a=np.append(a,[1,2,3,4])
print(a)

[0 1 2 3 4]


In [ ]:
a=np.array([1,2,3,4])
a=np.append(a,7)
print(a)

[1 2 3 4 7]


In [ ]:
a=np.array([1,2,3,4,5,6])
a=np.delete(a,[2,3])
print(a)

[1 2 5 6]


In [ ]:
a=[0]
a=np.append([1,2,3,4,5],a)
print(a)

[1 2 3 4 5 0]


In [ ]:
a=np.array([1,8,9,-3,2,4,7,9])
print(np.where(a>=a[np.argmax(a)])[0])

[2 7]


In [ ]:
a=np.array([[1,2],[3,1]])
print(np.where(a>1)[0])

[0 1]


In [ ]:
a=np.array([[8,2,1],[7,5,8],[6,2,7]])
a=np.sort(a,axis=1,kind='quicksort') #axis=0(column)
print(a)

[[1 2 8]
 [5 7 8]
 [2 6 7]]


In [ ]:
%%time
a=np.sum(a)
a

CPU times: user 137 µs, sys: 11 µs, total: 148 µs
Wall time: 154 µs


46

In [ ]:
a=np.array([[1,2],[2,3]])
b=np.array([[1,2],[3,2]])
print(a.dot(b))

[[ 7  6]
 [11 10]]


In [ ]:
print(a @ b)   #dot product

[[ 7  6]
 [11 10]]


In [ ]:
x=np.array([[1,2],[2,3],[2,6],[8,7]])
x.reshape(4,2)
x

array([[1, 2],
       [2, 3],
       [2, 6],
       [8, 7]])

In [ ]:
w=np.array([[1,1],[2,3]])
print(w)

[[1 1]
 [2 3]]


In [ ]:
z=w.squeeze()
print(z)
z.shape

[[1 1]
 [2 3]]


(2, 2)

squeeze-remove unncessary brackets
broadcasting-extend
1.if the two arrays differ  padded with ones on its leading(left)side
2.if the shape of the two arrays does not match in any dimesions,the array

In [ ]:
a=np.array([[1],[2],[3]])
b=np.array([[1,2],[2,3],[3,4]])
c=a+b
c

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
a=np.numpy([[1,2],[3,4]])

In [ ]:
a=np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [ ]:
vertical=np.vstack((a,a))
a

array([[1., 0.],
       [0., 1.]])

In [ ]:
horz=np.hstack((a,a))
a

array([[1., 0.],
       [0., 1.]])

In [ ]:
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
b=a[1,2]
b

6

In [ ]:
a=np.array([[1],[2],[3]])
b=np.array([[4],[2],[6]])
c=a+b
print(c)

[[5]
 [4]
 [9]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=a*2
print(b)

[[2 4]
 [6 8]]


In [ ]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3,1)
b

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [ ]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15],[16, 17, 18]],[[19, 20, 21],[22, 23, 24],[25, 26, 27]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
mean=np.mean(a)
mean

14.0

In [ ]:
standard_deviation=np.std(a)
standard_deviation

7.788880963698615

In [ ]:
min=np.min(a)
min

1

In [ ]:
max=np.max(a)
max

27

In [ ]:
o=np.arange(27)
three=o.reshape(3,3,3)
three

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
n=a[:1, :3]
n

array([[1, 2, 3]])

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
s=a[:2,2:]
s

array([[3, 4],
       [7, 8]])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
con=np.concatenate((a,b),axis=0)
print(con)

[1 2 3 4 5 6]


In [ ]:
stackv=np.vstack((a,b))
stackv

array([[1, 2, 3],
       [4, 5, 6]])